const API_BASE_URL_DEVELOPMENT = "http://192.168.102.6:3000";
const API_BASE_URL_NGROK =
  "https://c248-2001-ee0-50d0-bb70-71ab-7766-5b1b-37d9.ap.ngrok.io";

const ENDPOINTS = {
  LOGIN: "api/admins/login",
  GET_ALL_USERS: "api/admins/getall",
  GET_ALL_CITIES: "api/city/getall",
  APPLY: "api/candidate/apply",
};

const DEVELOPMENT = {
  API_URL_LOGIN: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.LOGIN}`,
  API_URL_CREATE_CATEGORY: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.CREATE_CATEGORY}`,
  API_URL_GET_ALL_USER: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_ALL_USERS}`,
  API_URL_GET_ALL_CITY: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_ALL_CITIES}`,
  API_URL_APPLY: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.APPLY}`,
};

const DEVELOPMENT_NGROK = {
  API_URL_LOGIN: `${API_BASE_URL_NGROK}/${ENDPOINTS.LOGIN}`,
  API_URL_GET_ALL_USER: `${API_BASE_URL_NGROK}/${ENDPOINTS.GET_ALL_USERS}`,
  API_URL_GET_ALL_CITY: `${API_BASE_URL_NGROK}/${ENDPOINTS.GET_ALL_CITIES}`,
  API_URL_APPLY: `${API_BASE_URL_NGROK}/${ENDPOINTS.APPLY}`,
};

const Constants = DEVELOPMENT;
// const Constants = DEVELOPMENT_NGROK;

export default Constants;
