const API_BASE_URL_DEVELOPMENT = "http://192.168.102.6:3000";

const ENDPOINTS = {
  REGISTER: "api/users/register",
  LOGIN: "api/admins/login",
  CREATE_CATEGORY: "api/category",
  GET_ALL_USERS: "api/admins/getall",
};

const DEVELOPMENT = {
  API_URL_REGISTER: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.REGISTER}`,
  API_URL_LOGIN: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.LOGIN}`,
  API_URL_CREATE_CATEGORY: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.CREATE_CATEGORY}`,
  API_URL_GET_ALL_USER: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_ALL_USERS}`,
};

const Constants = DEVELOPMENT;

export default Constants;
